# Generated by Django 4.1.7 on 2023-03-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richiesta_appuntamento', models.TextField(blank=True)),
                ('data_richiesta', models.DateField(auto_now_add=True)),
                ('accettazione', models.BooleanField(default=False)),
                ('data_accettata', models.DateField(blank=True, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appuntamenti',
            },
        ),
    ]
