# Generated by Django 4.1.7 on 2023-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citta', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=200)),
                ('stato', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
