# Generated by Django 4.1.7 on 2023-03-01 16:40

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Animali',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('venditore', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('prezzo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('immagine', models.ImageField(default='static/prodotti/3298693.png', upload_to='static/uploads/')),
                ('in_stock', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('in_promo', models.BooleanField(default=False)),
                ('cucciolo', models.BooleanField(default=True)),
                ('adulto', models.BooleanField(default=True)),
                ('anziano', models.BooleanField(default=True)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('animale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_online.animale')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_online.categoria')),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(blank=True)),
                ('valore', models.PositiveIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
                ('data_pub', models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 40, 13, 524817))),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_online.prodotto')),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
                'ordering': ['-data_pub'],
            },
        ),
    ]
